type: object
properties:
  resourcePoolId:
    type: string
    description: id of the resource group to be used, can be prefixed with `pool-`. A resource pool group can be specified instead by prefixing its ID with `poolGroup-`.
  availabilityOptions:
    type: string
    description: Availability Options
    enum:
      - "zone"
      - "set"
  availabilitySet:
    type: string
    description: Availability Set
  availabilityZone:
    type: integer
    format: int64
    description: Availability Zone
  azurefloatingIp:
    type: string
    description: Assign Public IP
    enum:
      - "on"
      - "off"
  bootDiagnostics:
    type: string
    description: Boot Diagnostics
    enum:
      - "enable"
      - "enable_custom_storage"
  osGuestDiagnostics:
    type: string
    description: OS Guest Diagnostics
    enum:
      - "on"
      - "off"
  diagnosticsStorageAccount:
    type: string
    description: Diagnostics Storage Account
  createUser:
    type: boolean
    description: Create User
    default: true
  imageId:
    type: integer
    format: int64
    description: Virtual Image ID